services:
  - type: web
    name: property-plug
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/property-plug-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev 